function [Flowsensor, Pressuresensor] = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [VARNAME4, VARNAME6] = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [VARNAME4, VARNAME6] = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [VarName4, VarName6] = importfile("C:\Users\Joeri\Documents\Facemask_project\measurement_1_sample_1.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Apr-2020 14:48:00

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "VarName4", "Var5", "VarName6", "Var7", "Var8"];
opts.SelectedVariableNames = ["VarName4", "VarName6"];
opts.VariableTypes = ["string", "string", "string", "double", "string", "double", "string", "string"];
opts = setvaropts(opts, [1, 2, 3, 5, 7, 8], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2, 3, 5, 7, 8], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
Flowsensor = tbl.VarName4;
Pressuresensor = tbl.VarName6;
end